# Config file for automatic testing at travis-ci.org

language: python
dist: bullseye

python:
  - "3.11"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg
  - pip install flit

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: flit install -s

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source cast runtests.py

after_success:
  - codecov -e TOX_ENV
