# Generated by Django 4.1.7 on 2023-03-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cast", "0038_alter_episode_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="noindex",
            field=models.BooleanField(
                default=False,
                help_text="Whether to add a noindex meta tag to this page and all subpages.",
                verbose_name="noindex",
            ),
        ),
    ]
