# Generated by Django 6.0.2 on 2026-03-06 20:43

import hashlib

from django.db import migrations, models


def build_gallery_signature(image_ids):
    normalized_image_ids = sorted(set(image_ids))
    if not normalized_image_ids:
        return ""
    signature_input = ",".join(str(image_id) for image_id in normalized_image_ids)
    return hashlib.sha256(signature_input.encode("ascii")).hexdigest()


def populate_gallery_signatures(apps, schema_editor):
    Gallery = apps.get_model("cast", "Gallery")
    galleries = Gallery.objects.prefetch_related("images").all()
    for gallery in galleries.iterator():
        signature = build_gallery_signature(image.pk for image in gallery.images.all())
        Gallery.objects.filter(pk=gallery.pk).update(signature=signature)


class Migration(migrations.Migration):

    dependencies = [
        ("cast", "0062_alter_transcript_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="signature",
            field=models.CharField(blank=True, db_index=True, default="", editable=False, max_length=64),
        ),
        migrations.RunPython(populate_gallery_signatures, migrations.RunPython.noop),
    ]
