# Generated by Django 5.2.4 on 2026-03-12 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0063_gallery_signature'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoxhelmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_base', models.URLField(blank=True, help_text='Voxhelm service root or /v1 API base, for example https://voxhelm.example.com.', verbose_name='API base URL')),
                ('api_token', models.CharField(blank=True, help_text='Bearer token used for Voxhelm job submission and artifact access.', max_length=255, verbose_name='API token')),
                ('model', models.CharField(blank=True, default='', help_text='Optional Voxhelm model preference. Leave blank to use the default "auto".', max_length=128)),
                ('language', models.CharField(blank=True, default='', help_text='Optional language hint sent to Voxhelm jobs.', max_length=32)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Voxhelm settings',
            },
        ),
    ]
