# Generated by Django 6.0.5 on 2026-05-16 22:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0065_transcriptgeneration'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='The public contributor name.', max_length=128)),
                ('slug', models.SlugField(help_text='Stable identifier for this contributor.', unique=True)),
                ('visible', models.BooleanField(default=True, help_text='Globally hide this contributor from public episode pages and podcast feeds.')),
                ('short_bio', models.TextField(blank=True, help_text='Optional short public biography.')),
                ('avatar', models.ForeignKey(blank=True, help_text='Optional public contributor avatar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ContributorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('service', models.CharField(choices=[('website', 'Website'), ('github', 'GitHub'), ('mastodon', 'Mastodon'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], default='website', max_length=32)),
                ('url', models.URLField(max_length=500)),
                ('contributor', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cast.contributor')),
            ],
            options={
                'verbose_name': 'Contributor link',
                'verbose_name_plural': 'Contributor links',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EpisodeContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('role', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], default='guest', max_length=32)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episode_assignments', to='cast.contributor')),
                ('episode', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_assignments', to='cast.episode')),
                ('link', models.ForeignKey(blank=True, help_text='Optional contributor link to use for this episode and feed item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cast.contributorlink')),
            ],
            options={
                'verbose_name': 'Episode contributor',
                'verbose_name_plural': 'Episode contributors',
                'ordering': ['sort_order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('episode', 'contributor', 'role'), name='unique_episode_contributor_role')],
            },
        ),
    ]
