# Generated by Django 6.0.5 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cast", "0066_contributor_contributorlink_episodecontributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="voxhelmsettings",
            name="diarization_enabled",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text=(
                    "Leave unset to use Django settings or environment variables. Enable to request Voxhelm speaker "
                    "diarization for this site. Disable to explicitly turn it off for this site."
                ),
                null=True,
                verbose_name="Speaker diarization",
            ),
        ),
    ]
