# Generated by Django 6.0.5 on 2026-05-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cast", "0067_voxhelmsettings_diarization_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributor",
            name="default_role",
            field=models.CharField(
                choices=[("host", "Host"), ("guest", "Guest")],
                default="guest",
                help_text="Default role to use when this contributor is added to an episode.",
                max_length=32,
            ),
        ),
    ]
