# Generated by Django 6.0.5 on 2026-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0068_contributor_default_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='transcript_diarization_mode',
            field=models.CharField(choices=[('inherit', 'Inherit'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='inherit', help_text='Controls speaker diarization for transcript generation and public speaker-label display for this audio. Disabling keeps transcript text and timestamps, hides any stored speaker labels publicly, and future generations will not request speaker diarization. This audio transcript may be shared by multiple episodes.', max_length=16),
        ),
    ]
