# Generated by Django 6.0.5 on 2026-05-28 22:33

import cast.models.contributors
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0069_audio_transcript_diarization_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorVoiceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, help_text='Optional internal label for this reference.', max_length=128)),
                ('clip', models.FileField(blank=True, help_text='Uploaded clean solo clip. Use protected storage; do not expose publicly.', null=True, storage=cast.models.contributors.get_voice_reference_storage, upload_to='cast_voice_references/')),
                ('start_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('end_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='pending', help_text='References start as pending and must be approved before Voxhelm use.', max_length=32)),
                ('consent_confirmed', models.BooleanField(default=False, help_text='Confirms the contributor consented to voice-reference use. Required to approve.')),
                ('allow_for_hidden_contributor', models.BooleanField(default=False, help_text='Allow known-speaker use for public transcripts even if the contributor is hidden.')),
                ('notes', models.TextField(blank=True, help_text='Optional reviewer notes.')),
                ('contributor', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_references', to='cast.contributor')),
                ('source_audio', models.ForeignKey(blank=True, help_text='Audio the source range points into. Required for source-range references.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cast.audio')),
                ('source_episode', models.ForeignKey(blank=True, help_text='Optional episode this reference was captured from, for editorial context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cast.episode')),
            ],
            options={
                'verbose_name': 'Contributor voice reference',
                'verbose_name_plural': 'Contributor voice references',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
