# Generated by Django 6.0.5 on 2026-05-29 05:40

import cast.models.contributors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0070_contributorvoicereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='speakers',
            field=models.FileField(blank=True, help_text='Private known-speaker suggestions returned by Voxhelm: per-segment candidates, confidence, margin, uncertainty, and raw diarization labels. Reviewable editorial state, never public transcript output.', null=True, storage=cast.models.contributors.get_voice_reference_storage, upload_to='cast_transcript_speakers/', verbose_name='Known-speaker suggestions'),
        ),
        migrations.AddField(
            model_name='voxhelmsettings',
            name='known_speaker_enabled',
            field=models.BooleanField(blank=True, default=None, help_text='Leave unset to use Django settings or environment variables. Enable to send approved contributor voice references for known-speaker recognition when diarization runs. Returned speaker identities remain reviewable suggestions and are not shown publicly until approved.', null=True, verbose_name='Known-speaker recognition'),
        ),
    ]
