# Generated by Codex on 2026-05-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cast", "0071_transcript_speakers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptSpeakerMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("speaker_label", models.CharField(max_length=256)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="One-off public name for this transcript speaker label.",
                        max_length=128,
                    ),
                ),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("unmapped", "Unmapped"),
                            ("approved", "Approved"),
                            ("stale", "Needs review"),
                        ],
                        default="unmapped",
                        max_length=32,
                    ),
                ),
                ("source_artifact_fingerprint", models.CharField(blank=True, max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reusable contributor target for this raw transcript speaker label.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cast.contributor",
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_mappings",
                        to="cast.transcript",
                    ),
                ),
            ],
            options={
                "ordering": ("transcript_id", "-active", "speaker_label"),
            },
        ),
        migrations.AddConstraint(
            model_name="transcriptspeakermapping",
            constraint=models.UniqueConstraint(
                fields=("transcript", "speaker_label"),
                name="unique_transcript_speaker_label",
            ),
        ),
    ]
