# Generated by Django 6.0.5 on 2026-05-30 18:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0072_transcriptspeakermapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=wagtail.fields.StreamField([('overview', 0), ('detail', 1)], block_lookup={0: ('cast.models.pages.ContentBlock', [], {'section': 'overview'}), 1: ('cast.models.pages.ContentBlock', [], {'section': 'detail'})}),
        ),
    ]
