# Generated by Django 6.0.5 on 2026-06-18 15:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cast", "0073_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="episode_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional positive episode number used as podcast publishing metadata.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="episode_type",
            field=models.CharField(
                blank=True,
                choices=[("full", "Full"), ("trailer", "Trailer"), ("bonus", "Bonus")],
                default="",
                help_text="Optional podcast episode type. Leave blank to omit the feed tag; blank is equivalent to full.",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Positive season number used in podcast feeds.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional season name for Podcasting 2.0 feeds.",
                        max_length=128,
                    ),
                ),
                (
                    "podcast",
                    models.ForeignKey(
                        help_text="Podcast this season belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="cast.podcast",
                    ),
                ),
            ],
            options={
                "ordering": ["podcast_id", "number"],
            },
        ),
        migrations.AddField(
            model_name="episode",
            name="season",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional podcast season. It must belong to this episode's podcast.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cast.season",
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("podcast", "number"), name="unique_podcast_season_number"
            ),
        ),
    ]
