# Generated by Django 6.0.5 on 2026-06-18 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cast", "0074_episode_episode_number_episode_episode_type_season_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="automatic_episode_numbering_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Assign the next podcast-scoped number to blank full episodes on their first publish.",
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="next_episode_number",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Next number to try when automatic episode numbering is enabled.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
