# Generated by Django 6.0.5 on 2026-07-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cast", "0078_private_voice_reference_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="itunes_type",
            field=models.CharField(
                blank=True,
                choices=[("episodic", "Episodic"), ("serial", "Serial")],
                default="",
                help_text="Optional Apple Podcasts channel ordering type. Leave blank to omit the feed tag.",
                max_length=16,
                verbose_name="iTunes type",
            ),
        ),
    ]
