# Generated by Django 6.0.5 on 2026-07-07 15:06

from __future__ import annotations

import json
from typing import Any

from django.db import migrations
from django.utils.html import escape


def _convert_heading_block(block: dict[str, Any]) -> None:
    value = block.get("value")
    text = escape(value) if isinstance(value, str) else ""
    block["type"] = "paragraph"
    block["value"] = f"<h2>{text}</h2>"


def convert_heading_blocks(value: Any) -> bool:
    """Convert stored heading StreamField JSON in place, returning whether it changed."""
    if not isinstance(value, list):
        return False

    changed = False
    for block in value:
        if not isinstance(block, dict):
            continue
        block_type = block.get("type")
        if block_type == "heading":
            _convert_heading_block(block)
            changed = True
        elif block_type in {"overview", "detail"}:
            changed = convert_heading_blocks(block.get("value")) or changed
    return changed


def _update_streamfield_json(model: type[Any], pk: Any, body: Any, schema_editor: Any) -> None:
    """Write StreamField JSON directly, avoiding StreamField/block deserialization."""
    connection = schema_editor.connection
    field = model._meta.get_field("body")
    table_name = model._meta.db_table
    pk_column = model._meta.pk.column
    body_column = field.column
    adapted_body = connection.ops.adapt_json_value(body, getattr(field, "encoder", None))

    with connection.cursor() as cursor:
        cursor.execute(
            "UPDATE {table} SET {body_column} = %s WHERE {pk_column} = %s".format(
                table=connection.ops.quote_name(table_name),
                body_column=connection.ops.quote_name(body_column),
                pk_column=connection.ops.quote_name(pk_column),
            ),
            [adapted_body, pk],
        )


def _load_json(value: Any) -> Any:
    if isinstance(value, str):
        return json.loads(value)
    return value


def _convert_live_bodies(model: type[Any], schema_editor: Any) -> None:
    connection = schema_editor.connection
    field = model._meta.get_field("body")
    table_name = model._meta.db_table
    pk_column = model._meta.pk.column
    body_column = field.column

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT {pk_column}, {body_column} FROM {table}".format(
                pk_column=connection.ops.quote_name(pk_column),
                body_column=connection.ops.quote_name(body_column),
                table=connection.ops.quote_name(table_name),
            )
        )
        rows = cursor.fetchall()

    for pk, raw_body in rows:
        body = _load_json(raw_body)
        if convert_heading_blocks(body):
            _update_streamfield_json(model, pk, body, schema_editor)


def _convert_revisions(apps: Any) -> None:
    from django.apps import apps as global_apps
    from django.db.models import Q

    from cast.models import HomePage, Post

    ContentType = apps.get_model("contenttypes", "ContentType")
    Revision = apps.get_model("wagtailcore", "Revision")
    target_labels = {
        (model._meta.app_label, model._meta.model_name)
        for model in global_apps.get_models()
        if issubclass(model, Post) or issubclass(model, HomePage)
    }
    query = Q()
    for app_label, model_name in target_labels:
        query |= Q(app_label=app_label, model=model_name)
    content_type_ids = list(ContentType.objects.filter(query).values_list("pk", flat=True)) if target_labels else []

    for row in Revision.objects.filter(content_type_id__in=content_type_ids).values("pk", "content").iterator():
        content = row["content"]
        if not isinstance(content, dict) or "body" not in content:
            continue
        if convert_heading_blocks(content["body"]):
            Revision.objects.filter(pk=row["pk"]).update(content=content)


def forward(apps: Any, schema_editor: Any) -> None:
    Post = apps.get_model("cast", "Post")
    HomePage = apps.get_model("cast", "HomePage")

    _convert_live_bodies(Post, schema_editor)
    _convert_live_bodies(HomePage, schema_editor)
    _convert_revisions(apps)


class Migration(migrations.Migration):
    dependencies = [
        ("cast", "0079_podcast_itunes_type"),
    ]

    operations = [
        # Intentionally irreversible: old heading levels were never stored, so
        # converted rich-text paragraphs cannot be losslessly restored.
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
