# Generated by Django 6.0.5 on 2026-07-07 15:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cast", "0080_convert_heading_to_paragraph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("image", 1), ("gallery", 3)],
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "cast.blocks.CastImageChooserBlock",
                        (),
                        {"template": "cast/image/image.html"},
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("cast.blocks.GalleryBlock", (2,), {}),
                },
            ),
        ),
    ]
