"""Repository pattern for efficient data fetching and rendering."""

from wagtail.models import Site

from .builders import (
    _blog_url_from_referer,
    add_queryset_data,
    add_root_nav_links,
    add_site_raw,
    apply_cover_fallback,
    data_for_blog_cachable,
    get_facet_choices,
)
from .contexts import BlogIndexRepository, EpisodeFeedRepository, FeedRepository, PostDetailRepository
from .serialization import (
    audio_to_dict,
    blog_from_data,
    blog_to_dict,
    deserialize_renditions,
    episode_to_dict,
    image_to_dict,
    post_to_dict,
    rendition_to_dict,
    serialize_renditions,
    transcript_to_dict,
    video_to_dict,
)
from .snapshot import QuerysetData, cache_page_url
from .types import (
    AudioById,
    AudiosByPostID,
    Choice,
    CoverAltByPostID,
    CoverURLByPostID,
    HasAudioByID,
    HasChoices,
    ImageById,
    ImagesByPostID,
    LinkTuples,
    PageUrlByID,
    PostByID,
    RenditionsForPost,
    RenditionsForPosts,
    SerializedRenditions,
    TranscriptByAudioId,
    VideoById,
    VideosByPostID,
)

__all__ = [
    "AudioById",
    "AudiosByPostID",
    "BlogIndexRepository",
    "Choice",
    "CoverAltByPostID",
    "CoverURLByPostID",
    "EpisodeFeedRepository",
    "FeedRepository",
    "HasAudioByID",
    "HasChoices",
    "ImageById",
    "ImagesByPostID",
    "LinkTuples",
    "PageUrlByID",
    "PostByID",
    "PostDetailRepository",
    "QuerysetData",
    "RenditionsForPost",
    "RenditionsForPosts",
    "SerializedRenditions",
    "Site",
    "TranscriptByAudioId",
    "VideoById",
    "VideosByPostID",
    "_blog_url_from_referer",
    "add_queryset_data",
    "add_root_nav_links",
    "add_site_raw",
    "apply_cover_fallback",
    "audio_to_dict",
    "blog_from_data",
    "blog_to_dict",
    "cache_page_url",
    "data_for_blog_cachable",
    "deserialize_renditions",
    "episode_to_dict",
    "get_facet_choices",
    "image_to_dict",
    "post_to_dict",
    "rendition_to_dict",
    "serialize_renditions",
    "transcript_to_dict",
    "video_to_dict",
]
