from __future__ import annotations

from cast.models.transcript import Transcript
from cast.models.transcript_generation import TranscriptGeneration
from cast.transcripts.generation_status import (
    get_transcript_generation,
    get_transcript_generation_status_context,
    transcript_complete,
)

from .client import (
    KNOWN_SPEAKER_STRATEGY,
    MAX_VOXHELM_API_RESPONSE_BYTES,
    MAX_VOXHELM_ARTIFACT_BYTES,
    MAX_VOXHELM_ERROR_BYTES,
    TERMINAL_JOB_STATES,
    NoRedirectHandler,
    VoxhelmClient,
    normalize_api_base,
    open_url,
    read_http_error_detail,
    read_response_bytes,
)
from .exceptions import VoxhelmError
from .service import (
    DOTE_REQUIRED_KEYS,
    TranscriptEnqueueResult,
    TranscriptGenerationResult,
    TranscriptSubmission,
    VoxhelmTranscriptService,
    build_failure_message,
    build_known_speaker_reference_entry,
    build_known_speaker_references,
    client_diarization_enabled,
    client_known_speaker_enabled,
    count_episode_diarization_speakers,
    enqueue_audio_transcript_generation,
    optional_artifact_path,
    parse_json_artifact,
    replace_file,
    require_artifact_path,
    resolve_audio_diarization_enabled,
    resolve_audio_source_url,
    resolve_diarization_speaker_count,
    validate_dote_artifact,
    validate_json_list_artifact,
    validate_podlove_artifact,
    validate_transcript_artifacts,
    validate_vtt_artifact,
)
from .settings import (
    FALSE_SETTING_VALUES,
    SITE_SETTING_FIELD_MAP,
    TRUE_SETTING_VALUES,
    get_bool_setting,
    get_float_setting,
    get_setting,
    get_site_setting_value,
    require_setting,
    voxhelm_configured,
)
from .task_refs import (
    append_diarization_speaker_count_to_task_ref,
    build_audio_task_ref,
    ensure_diarized_task_ref,
    resolve_audio_task_ref,
    strip_diarized_task_ref,
)

__all__ = [
    "DOTE_REQUIRED_KEYS",
    "FALSE_SETTING_VALUES",
    "KNOWN_SPEAKER_STRATEGY",
    "MAX_VOXHELM_API_RESPONSE_BYTES",
    "MAX_VOXHELM_ARTIFACT_BYTES",
    "MAX_VOXHELM_ERROR_BYTES",
    "SITE_SETTING_FIELD_MAP",
    "TERMINAL_JOB_STATES",
    "TRUE_SETTING_VALUES",
    "NoRedirectHandler",
    "Transcript",
    "TranscriptEnqueueResult",
    "TranscriptGeneration",
    "TranscriptGenerationResult",
    "TranscriptSubmission",
    "VoxhelmClient",
    "VoxhelmError",
    "VoxhelmTranscriptService",
    "append_diarization_speaker_count_to_task_ref",
    "build_audio_task_ref",
    "build_failure_message",
    "build_known_speaker_reference_entry",
    "build_known_speaker_references",
    "client_diarization_enabled",
    "client_known_speaker_enabled",
    "count_episode_diarization_speakers",
    "enqueue_audio_transcript_generation",
    "ensure_diarized_task_ref",
    "get_bool_setting",
    "get_float_setting",
    "get_setting",
    "get_site_setting_value",
    "get_transcript_generation",
    "get_transcript_generation_status_context",
    "normalize_api_base",
    "open_url",
    "optional_artifact_path",
    "parse_json_artifact",
    "read_http_error_detail",
    "read_response_bytes",
    "replace_file",
    "require_artifact_path",
    "require_setting",
    "resolve_audio_diarization_enabled",
    "resolve_audio_source_url",
    "resolve_audio_task_ref",
    "resolve_diarization_speaker_count",
    "strip_diarized_task_ref",
    "transcript_complete",
    "validate_dote_artifact",
    "validate_json_list_artifact",
    "validate_podlove_artifact",
    "validate_transcript_artifacts",
    "validate_vtt_artifact",
    "voxhelm_configured",
]
