# Generated by Django 6.0.5 on 2026-06-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cast_comments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentAuthorMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_pk",
                    models.CharField(max_length=255, unique=True),
                ),
                ("edited", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Comment author metadata",
                "verbose_name_plural": "Comment author metadata",
            },
        ),
    ]
