# Generated by Django 2.1.3 on 2018-11-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cast", "0004_auto_20181109_0941")]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="flac",
            field=models.FileField(blank=True, null=True, upload_to="cast_audio/"),
        ),
        migrations.AddField(
            model_name="audio",
            name="mp4",
            field=models.FileField(blank=True, null=True, upload_to="cast_audio/"),
        ),
        migrations.AlterField(
            model_name="audio",
            name="mp3",
            field=models.FileField(blank=True, null=True, upload_to="cast_audio/"),
        ),
    ]
