# Generated by Django 2.1.3 on 2018-11-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cast", "0005_auto_20181109_1134")]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="subtitle",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="audio",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
