# Generated by Django 2.0.9 on 2018-11-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cast", "0007_post_podcast")]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="podcast", new_name="podcast_audio"
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cast.Image",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="audios",
            field=models.ManyToManyField(blank=True, to="cast.Audio"),
        ),
        migrations.AlterField(
            model_name="post",
            name="galleries",
            field=models.ManyToManyField(blank=True, to="cast.Gallery"),
        ),
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(blank=True, to="cast.Image"),
        ),
        migrations.AlterField(
            model_name="post",
            name="videos",
            field=models.ManyToManyField(blank=True, to="cast.Video"),
        ),
    ]
