# Generated by Django 2.0.9 on 2018-11-19 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("cast", "0008_auto_20181119_1107")]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        )
    ]
