# Generated by Django 2.0.9 on 2018-11-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cast", "0019_auto_20181120_1024")]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="keywords",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A comma-demlimitedlist of up to 12 words for iTunes\n            searches. Perhaps include misspellings of the title.",
                max_length=255,
                verbose_name="keywords",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="keywords",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A comma-demlimitedlist of up to 12 words for iTunes\n            searches. Perhaps include misspellings of the title.",
                max_length=255,
                verbose_name="keywords",
            ),
        ),
    ]
