# Generated by Django 2.1.7 on 2019-03-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cast", "0021_auto_20190225_2317")]

    operations = [
        migrations.CreateModel(
            name="ChapterMark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.CharField(max_length=12)),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField(blank=True, max_length=2000, null=True)),
                ("image", models.URLField(blank=True, max_length=2000, null=True)),
                (
                    "audio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chaptermarks",
                        to="cast.Audio",
                    ),
                ),
            ],
        )
    ]
