# Generated by Django 2.2 on 2019-04-15 13:11

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0023_auto_20190415_0803'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chaptermark',
            constraint=models.CheckConstraint(check=models.Q(start__lte=django.db.models.expressions.F('audio__duration')), name='start_lte_duration'),
        ),
    ]
