# Generated by Django 2.2 on 2019-05-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cast", "0025_auto_20190516_1102")]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        )
    ]
