# Generated by Django 2.2 on 2019-05-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cast", "0026_blog_author")]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField()),
                ("status", models.PositiveSmallIntegerField()),
                ("size", models.PositiveIntegerField()),
                ("referer", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "method",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "GET"),
                            (2, "HEAD"),
                            (3, "POST"),
                            (4, "PUT"),
                            (5, "PATCH"),
                            (6, "DELETE"),
                            (7, "OPTIONS"),
                            (8, "CONNECT"),
                            (8, "TRACE"),
                        ]
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                (
                    "protocol",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "HTTP/1.0"), (2, "HTTP/1.1"), (3, "HTTP/2.0")]
                    ),
                ),
            ],
        )
    ]
