# Generated by Django 2.2 on 2019-05-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cast", "0027_request")]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="referer",
            field=models.CharField(blank=True, max_length=2048, null=True),
        )
    ]
