# Generated by Django 4.1.4 on 2023-02-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cast", "0030_remove_pub_date_is_handled_by_wagtail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created",
        ),
        migrations.RemoveField(
            model_name="post",
            name="modified",
        ),
    ]
