# Generated by Django 3.0.4 on 2020-03-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0030_auto_20200330_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
    ]
