# Generated by Django 5.0.4 on 2024-04-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cast", "0055_alter_podcast_itunes_artwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="template_base_dir",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bootstrap4", "Bootstrap 4"),
                    ("plain", "Just HTML"),
                    ("vue", "Vue.js"),
                    ("bootstrap5", "Bootstrap 5"),
                    ("pp", "Python Podcast"),
                ],
                default=None,
                help_text="The theme to use for this blog implemented as a template base directory. If not set, the template base directory will be determined by a site setting.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="templatebasedirectory",
            name="name",
            field=models.CharField(
                choices=[
                    ("bootstrap4", "Bootstrap 4"),
                    ("plain", "Just HTML"),
                    ("vue", "Vue.js"),
                    ("bootstrap5", "Bootstrap 5"),
                    ("pp", "Python Podcast"),
                ],
                default="bootstrap4",
                help_text="The theme to use for this site implemented as a template base directory. It's possible to overwrite this setting for each blog.If you want to use a custom theme, you have to create a new directory in your template directory named cast/<your-theme-name>/ and put all required templates in there.",
                max_length=128,
            ),
        ),
    ]
